### ISSUE TITLE
UPA 

### ISSUE THREAD

**Issue by SirineMili** [thevpc/upa#3]
When running my  project using UPA , I get the error below for this usage of @Formula  statement:

`@Formula("if this.quality=true then this.tcvLoad else 0 end ")
`
[ org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vr': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private net.vpc.app.vainruling.core.service.CorePlugin net.vpc.app.vainruling.core.web.Vr.core; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vrApp': Invocation of init method failed; nested exception is net.vpc.upa.exceptions.UPAException: InvalidFormulaExpression(InspectionOil.vesselTCV,PersistFormula,if this.quality=true then this.tcvLoad else 0 end )](url)

**Comment by thevpc** [comment]
Problem is fixed in 1.2.0.44
